### ISSUE TITLE
Ngram left/right/any

### ISSUE THREAD

**Issue by rebeckahw** [humlab-swedeb/swedeb-api#18]
Add support for requesting n-grams with search placed to the left, the right or in any position in the result.  Modify tool_router.py and ngrams.py

**Comment by roger-mahler** [comment]
Add n-gram alignment to n-gram domain service.

**Comment by rebeckahw** [comment]
Alignment support added to api for n-grams

https://github.com/humlab-swedeb/swedeb-api/blob/0c5749e7e94fc2a39483a4269fe0eee65595b0e6/api_swedeb/api/path_enums.py#L4C1-L7C16

**Comment by roger-mahler** [comment]
Ok, the solution added in PR #65 doesn't use the "Position" schema meantioned above. For now it just accepts string values "sliding", "left_aligned" and "right_aligned". It should be easy to fix though.
