### ISSUE TITLE
Problem with party connection to speeches

### ISSUE THREAD

**Issue by fredrik1984** [humlab-swedeb/swedeb-api#74]
After Fredrik updated the party name Excel file (incl party abbreviations) Roger made a first attempt to implement this new party name structure in SweDeb. However, there is currently a problem with connections between parties and speakers/speeches. 

Some examples:

Many (all?) searchers for speeches with parties before 1900 don't get any results at all in the tool Anföranden.

When I search for speeches (in the tool Anföranden) by MPs that belong to AK:s centern (1873–1882) / AK-c73, I only get speeches from Centern (that is the contemporary Centerpartiet).

Also using the other tools (word trends and kwic) and searching for words before 1900 get no results with party connections from this period.

I tag @roger-mahler and @rebeckahw here.

**Comment by fredrik1984** [comment]
Currently, it seems that two 19th century parties dominate among the incorrectly tagged speeches (in SweDeb, the Swerik data is correct): AK-c89 (286,000 speeches) and AK-c73 (69,000 speeches). There are also several of speeches in SweDeb incorrectly annotated with AK-mfg, AK-ch, and AK-bd.

**Comment by roger-mahler** [comment]
This is probably not an error, and will hopefully be resolved by an ongoing data reprocess.

The changes made to the party metadata require a partial reprocess of  some of the Swedeb metadata.

**Comment by fredrik1984** [comment]
ok, that sounds good!

**Comment by roger-mahler** [comment]
Reprocess done.
