### ISSUE TITLE
Change time interval in the word trend graph

### ISSUE THREAD

**Issue by fredrik1984** [humlab-swedeb/swedeb-api#76]
It would look nicer if the time interval in the word trend graph was based on decades or 5-year periods, e.g. 1870, 1880, 1890, etc, and 1875, 1880, 1885, etc. Hence, no matter in which year the data starts, the graph should always represent time markers like this.

**Comment by kpaalm** [comment]
fixed in frontend. time interval of ten years, 20 if the user has a small screen. 
Will be part of later update for you to look at.
