### ISSUE TITLE
Order party name filter function in a specific way

### ISSUE THREAD

**Issue by fredrik1984** [humlab-swedeb/swedeb-api#79]
When filtering for party name, the list of party names should be ordered in the following: first the current parties in the parliament (in alphabetic order), then all other (in alphabetic order). Here is the list:

Centerpartiet (1922–)
Kristdemokraterna (1985–)
Liberalerna (1900–)
Miljöpartiet (1988–)
Moderaterna (1935–)
Socialdemokraterna (1897–)
Sverigedemokraterna (2010–)
Vänsterpartiet (1917–)
AK:s bondeska diskussionsklubben (1897–1899)
AK:s center (1889–1894)
AK:s center-högern (1883–1886)
AK:s centern (1873–1882)
AK:s de moderata reformvännernas grupp (1903–1905)
AK:s folkpartiet (1895–1899)
AK:s friesenska diskussionsklubben (1897–1899)
AK:s frihandelsparti (1887–1888)
AK:s frihandelsvänliga centern (1895–1897)
AK:s frisinnade försvarsvänner (1914)
AK:s gamla lantmannapartiet (1888–1894)
AK:s lantmanna- och borgarepartiet (1912–1934)
AK:s lantmannapartiet (1867–1887, 1895–1911)
AK:s lantmannapartiets filial (1873–1887)
AK:s nationella framstegspartiet (1906–1911)
AK:s nationella gruppen (1935–1936)
AK:s nya centern (1883–1887)
AK:s nya centern (1895–1896)
AK:s nya lantmannapartiet (1888–1894)
AK:s nyliberala partiet (1868–1871)
AK:s vänstern (1886)
FK:s centern (1885–1887)
FK:s det förenade högerpartiet (1910–1911)
FK:s ehrenheimska partiet (1873–1887)
FK:s konservativa grupp (1867–1872)
FK:s ministeriella grupp (1867–1872)
FK:s ministeriella partiet (1867–1872)
FK:s minoritetsparti (1888–1904)
FK:s moderata parti (1905–1911)
FK:s nationella parti (1912–1934)
FK:s protektionistiska parti (1888–1909)
FK:s vänstern (1886)
Jordbrukarnas fria grupp (1918–1921)
Kilbomspartiet (1930–1933)
Liberala riksdagspartiet (1924–1934)
Medborgerlig samling (1964–1968)
Ny demokrati (1991–1994)
Socialistiska partiet (1934–1940)
Utan partibeteckning

**Comment by kpaalm** [comment]
resolved in frontend
