### ISSUE TITLE
Show number of hits for each word trend search

### ISSUE THREAD

**Issue by fredrik1984** [humlab-swedeb/swedeb-api#80]
To the word trend graph, for each chosen word the number of hits should be shown to the left of the graph where the different search words are shown. This should also include the total number of hits (black trend line).

**Comment by kpaalm** [comment]
Can now show total number of hits for each word, does not take into consideration if same word is said in the same speech (does not count speeches, counts total sayings). Added with pull request #67 in swedeb_frontend to dev.
