### ISSUE TITLE
Update info texts

### ISSUE THREAD

**Issue by fredrik1984** [humlab-swedeb/swedeb-api#87]
Fredrik and Johan will go through the SweDeb interface and update the information, including the FAQ page.

**Comment by fredrik1984** [comment]
In this Google Doc link, you will find suggestions for revised information text for the different pages in Riksdagsdebatter.se: 

https://docs.google.com/document/d/1gMfsGU_D-x_YtLrbZTjrjVaYQ7tDSuMqzcwTOxZqfHk/edit?tab=t.0

@kpaalm – I guess this is on your table to update when time is available.

**Comment by kpaalm** [comment]
I dokumentet finns en bild i en av faq. Skulle behöva den i bättre upplösning.
@fredrik1984

**Comment by fredrik1984** [comment]
Jag försökte skapa en ihopklistrad bild av detta sidouppslag från biografribanden över ledamöterna under tvåkammarriksdagen. @kpaalm – tror du att du att göra det med bättre upplösning?

[biografiträd från bok.pdf](https://github.com/user-attachments/files/17903893/biografitrad.fran.bok.pdf)

**Comment by kpaalm** [comment]
Kan ha löst något, bilden är inte direkt läsbar dock. Vill man zooma in för att försöka läsa får man öppna bilden i ny flik.
Vad vill du ha för alt-text och vill du ha någon bildtext till detta?

**Comment by fredrik1984** [comment]
ok, bra! vi kan väl börja så, både ha bilden inbäddad i texten + ha en separat länk till högre upplösning. vill först se det om det är värt att lägga till bildtext.

**Comment by kpaalm** [comment]
All updated, except Swedeb --> Riksdagsdebatter.se (need to wait until we actually have that URL)
Set as new issue of frontend#68
